databases:
  - name: bot-investasi-db
    databaseName: bot_investasi
    user: bot_user

services:
  - type: worker
    name: telegram-investment-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: bot-investasi-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
